CREATE TABLE IF NOT EXISTS chats
(
    id integer primary key generated by default as identity,
    name text not null unique,
    created timestamp with time zone
);

CREATE TABLE IF NOT EXISTS users
(
    id text primary key,
    name text not null unique,
    created timestamp with time zone
);

CREATE TABLE IF NOT EXISTS messages
(
    id integer primary key,
    chat_id integer,
    user_id text,
    reply_to_message_id integer,
    text text,
    created timestamp with time zone,
    constraint fk_chat
        foreign key(chat_id)
            references chats(id) ON UPDATE CASCADE,
    constraint fk_user
        foreign key(user_id)
            references users(id) ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_created on messages(created);
